inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'gemfiles/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
