name: Push Gem

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@master
    - name: Authenticate with Cloudsmith via OIDC
      uses: cloudsmith-io/cloudsmith-cli-action@v2
      with:
        oidc-namespace: "gusto"
        oidc-service-slug: "gusto-cloudsmith-write-svc-01"
        oidc-auth-only: "true"
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Publish to Cloudsmith
      run: |
        gem build *.gemspec
        GEM_HOST_API_KEY="Bearer ${CLOUDSMITH_API_KEY}" gem push *.gem --host https://cloudsmith.io/gusto/gusto
