name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4.x, 2.5.x, 2.6.x]
        appraisal: ["rails-4", "rails-5", "rails-6"]
    steps:
    - uses: actions/checkout@v1
    - name: Setup System
      run: |
        sudo apt-get install libsqlite3-dev
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec appraisal install
        bundle exec appraisal ${{ matrix.appraisal }} rake